parameters:
    netgen_toolbar.legacy_admin_siteaccess_name: ngadminui

services:
    netgen_toolbar.twig.global_variable:
        class: Netgen\Bundle\ToolbarBundle\Twig\GlobalVariable
        arguments:
            - "@router"
            - "@ibexa.config.resolver"
            - "%ngsite.admin_siteaccess_name%"
            - "%netgen_toolbar.legacy_admin_siteaccess_name%"
            - "%kernel.bundles%"
            - "@request_stack"